# gateway.nft.storage wrangler config.
name = "gateway-nft-storage"

# `javascript` means our we'll send pre-built javascript code. 
#  ...as opposed to `webpack` where wrangler builds our code for us.
type = "javascript"

account_id = ""
watch_dir = "src"
compatibility_date = "2021-12-03"

[build]
command = "npm run build"
[build.upload]
format = "modules"
dir = "dist"
main = "index.mjs"

# [vars]
# IPFS_GATEWAYS = "[\"https://ipfs.io\", \"https://cf-ipfs.com\", \"https://nft-storage.mypinata.cloud/\"]"
# DEBUG = "true"
# [durable_objects]
# bindings = [{name = "METRICS8", class_name = "Metrics8"}, {name = "CIDS1", class_name = "Cids1"}]

# PROD!
[env.production]
# name = "gateway-nft-storage-production"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
zone_id = "fc6cb51dbc2d0b9a729eae6a302a49c9"    # nft.storage zone
route = "*gateway.nft.storage/*"

[env.production.vars]
IPFS_GATEWAYS = "[\"https://ipfs.io\", \"https://cf-ipfs.com\", \"https://nft-storage.mypinata.cloud/\"]"
DEBUG = "false"

[env.production.durable_objects]
bindings = [{name = "METRICS8", class_name = "Metrics8"}, {name = "CIDS1", class_name = "Cids1"}]

# Staging!
[env.staging]
# name = "gateway-nft-storage-staging"
account_id = "fffa4b4363a7e5250af8357087263b3a" # Protocol Labs CF account
zone_id = "fc6cb51dbc2d0b9a729eae6a302a49c9"    # nft.storage zone
route = "*gateway-staging.nft.storage/*"

[env.staging.vars]
IPFS_GATEWAYS = "[\"https://ipfs.io\", \"https://cf-ipfs.com\", \"https://nft-storage.mypinata.cloud/\"]"
DEBUG = "true"

[env.staging.durable_objects]
bindings = [{name = "METRICS8", class_name = "Metrics8"}, {name = "CIDS1", class_name = "Cids1"}]

# Test!
[env.test]
workers_dev = true

[env.test.vars]
IPFS_GATEWAYS = "[\"http://localhost:9081\", \"http://localhost:9082\"]"
DEBUG = "true"

[env.test.durable_objects]
bindings = [{name = "METRICS8", class_name = "Metrics8"}, {name = "CIDS1", class_name = "Cids1"}]

# Dev!
[env.vsantos]
workers_dev = true
account_id = "7ec0b7cf2ec201b2580374e53ba5f37b"

[env.vsantos.vars]
IPFS_GATEWAYS = "[\"https://ipfs.io\"]"

[env.vsantos.durable_objects]
bindings = [{name = "METRICS8", class_name = "Metrics8"}, {name = "CIDS1", class_name = "Cids1"}]
